"""Prepare target graphs and batch-specific inherited plugins, without CUDA work."""
import argparse
import ast
import copy
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BATCHES = (1, 2, 4, 8, 16, 32, 64)

# These are batch roles, not arbitrary occurrences of the number 16.
BATCH_ROLES = {
    'dw_int8_plugin': ['grid_y=16*512'],
    'dw_int8_full_rewrite': ['(-1,16)'],
    'dw_int8_rewrite': ['(16,512,1)'],
    'online_branch_wide_plugin': ['grid_y=16'],
    'online_nonlinear_rna_plugin': ['grid_y=16'],
    'normal_tf32_plugin': ['grid_y=16'],
    'online_branch_stats_runtime_kernel': ['h*16+b'],
    'online_nonlinear_rna_runtime_kernel': ['h*16+b'],
    'normal_tf32_runtime_kernel': ['h*16+b'],
    'online_nlwide_rewrite': ['(4,16,', '(1,16,', '(16,-1)'],
    'normal_tf32_rewrite': ['(4,16,', '(1,16,', '(16,-1)'],
    'int8_nonlinear_value_runtime_kernel': ['T*16', 'm%16', 'm//16'],
    'int8_nonlinear_value_plugin': ['(16,512)', 'vd[1]=16', 'gd[1]=16', 'q.shape_expr[0]*16'],
    'int8_nonlinear_value_rewrite': ['(-1,16)', '(-1,16,512)', '[-1,16,512]', 'B16_view'],
    'i8_residual_aot': ['T*16'],
    'i8_residual_plugin': ['(16,48)', '(16,512)', 'shape[1]=16', 'q.shape_expr[0]*16'],
    'i8_residual_rewrite': ['(-1,16)', '(-1,16,48)', '(-1,16,512)', '[-1,16,48]', '[-1,16,512]', 'B16_view'],
}

def sha(path):
    with path.open('rb') as f:
        return hashlib.file_digest(f, 'sha256').hexdigest()

def runtime_package(code, batch, suffix=''):
    """Keep one application runner; expose generated batch-specific plugin ABIs."""
    parent=ROOT/'src/inspark_infer/ops/tensorrt/zipvoice/a1007'
    destination=parent/f'b{batch}{suffix}'
    destination.mkdir(parents=True,exist_ok=True)
    (parent/'__init__.py').write_text('"""A_1007 generated plugin namespaces."""\n')
    (destination/'__init__.py').write_text('"""Generated by scripts/prepare_zipvoice_a1007.py."""\n')
    names={p.stem for p in code.glob('*.py')}
    class Imports(ast.NodeTransformer):
        def visit_Import(self,node):
            converted=[]
            for alias in node.names:
                if alias.name in names:
                    converted.append(ast.ImportFrom(module=None,names=[alias],level=1))
                else:converted.append(ast.Import(names=[alias]))
            return converted
        def visit_ImportFrom(self,node):
            if node.module in names:node.level=1
            return node
    for path in code.glob('*.py'):
        tree=Imports().visit(ast.parse(path.read_text()))
        (destination/path.name).write_text(ast.unparse(ast.fix_missing_locations(tree))+'\n')

def prepare(batch):
    import onnx
    source_batch = 16 if batch <= 16 else batch
    target = ROOT / f'.work/zipvoice/b{batch}'
    code = target / 'code'
    code.mkdir(parents=True, exist_ok=True)
    provenance = {}
    for source in sorted((ROOT / f'src/inspark_infer/build/zipvoice_templates/b{source_batch}').glob('*.template')):
        name = source.name.removesuffix('.py.template')
        text = source.read_text()
        edits = []
        if batch < 16:
            for role in BATCH_ROLES.get(name, []):
                count = text.count(role)
                if not count:
                    raise ValueError(f'Missing batch role {name}: {role}')
                replacement = role.replace('16', str(batch))
                edits.append({'role':role,'replacement':replacement,'count':count})
                text = text.replace(role, replacement)
            text = text.replace('zipvoice_int8_b16', f'zipvoice_int8_b{batch}')
        ast.parse(text)
        dest = code / f'{name}.py'
        dest.write_text(text.rstrip()+'\n')
        provenance[name] = {'template_sha256':sha(source), 'generated_sha256':sha(dest),'batch_roles':edits}
    runtime_package(code,batch)
    graphs = target / 'graphs'
    graphs.mkdir(exist_ok=True)
    graph_records = {}
    for kind in ('fm-native','fm-inherited','text','vocos'):
        source = ROOT / f'models/zipvoice/onnx/{kind}.onnx'
        model = onnx.load(source, load_external_data=False)
        before = model.SerializeToString()
        changed = []
        for value in [*model.graph.input,*model.graph.output]:
            dim = value.type.tensor_type.shape.dim[0]
            if dim.dim_value == 64:
                dim.dim_value = batch
                changed.append(value.name)
        inverse = copy.deepcopy(model)
        for value in [*inverse.graph.input,*inverse.graph.output]:
            if value.name in changed:
                value.type.tensor_type.shape.dim[0].dim_value = 64
        assert inverse.SerializeToString() == before
        for tensor in model.graph.initializer:
            for item in tensor.external_data:
                if item.key == 'location':
                    import shutil
                    weight = source.parent / item.value
                    local = graphs / weight.name
                    if local.exists() and local.stat().st_nlink > 1:
                        local.unlink()
                    if not local.exists():
                        shutil.copyfile(weight, local)
                    item.value = local.name
        dest = graphs / f'{kind}.onnx'
        onnx.save(model, dest)
        profile = {}
        for value in model.graph.input:
            dims = [d.dim_value if d.dim_value else -1 for d in value.type.tensor_type.shape.dim]
            if -1 not in dims:
                continue
            bounds = {}
            for label,t,l in zip(('min','opt','max'),(600,760,920),(52,78,141)):
                if kind.startswith('fm'):
                    shape = [batch,1,1] if value.name in ('t','guidance_scale') else [batch,t] if value.name == 'padding_mask' else [batch,t,100]
                elif kind == 'text':
                    shape = [batch,l] if value.name == 'token_ids' else [1,t]
                else:
                    assert value.name == 'mel'
                    shape = [batch,100,t-375]
                bounds[label] = shape
            profile[value.name] = bounds
        (graphs/f'{kind}-profile.json').write_text(json.dumps(profile,indent=2)+'\n')
        graph_records[kind] = {'source_sha256':sha(source),'target_sha256':sha(dest),'batch_io_changes':changed,'inverse_protobuf_exact':True,'profile':profile}
    report = ROOT / f'reports/sm89/zipvoice/a1007/b{batch}/history/001-preparation.json'
    report.write_text(json.dumps({'batch':batch,'source_batch':source_batch,'plugins':provenance,'graphs':graph_records},indent=2)+'\n')
    print(f'Prepared B{batch}: {len(provenance)} inherited plugin/rewrite modules',flush=True)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--batches',type=int,nargs='+',choices=BATCHES,default=list(BATCHES))
    args = parser.parse_args()
    for batch in args.batches:
        prepare(batch)
